name: epp_build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cpp_prepare
        run: sudo apt install mingw-w64 -y
      - name: cmake_prepare
        run: sudo apt install cmake -y
      - name: bin_dir
        run: mkdir bin
      -name: cmake_config
        run: cmake --configure bin
      - name: make
        run: cmake --build bin
      - name: remove useless files
        run: rm -rf .git; rm -rf $(find . | grep ".cpp") ; rm -rf $(find . | grep ".h"); rm -rf $(find . | grep ".hpp")
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: build-all
          path: .